<a href="https://colab.research.google.com/github/iotpelican/ml-llm-course-work/blob/main/Matrix_Operations_with_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt # Although not used in this part, it's imported as per the user's initial setup.

# Define the matrices as specified in the problem description.
A = np.array([2, 4, 6])
B = np.arange(2, 17).reshape(3, 5)
C = np.ones((5, 6))
D = np.eye(5) # D is not used in this part, but defined as per the user's initial setup.

# Print the initial matrices to verify their structure.
print("--- Initial Matrices ---")
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("\n" + "="*30 + "\n") # Separator for better readability

# --- Part 1: Working with Matrices ---

# 1. Compute 5A + 2
# This involves scalar multiplication of matrix A by 5, and then adding 2 to each element.
result_5A_plus_2 = 5 * A + 2
print("1. Result of 5A + 2:\n", result_5A_plus_2)
print("\n" + "="*30 + "\n")

# 2. Compute the sum of each row in matrix B.
# Using np.sum() with axis=1 sums elements across columns for each row.
row_sums_B = np.sum(B, axis=1)
print("2. Sum of each row in Matrix B:\n", row_sums_B)
print("\n" + "="*30 + "\n")

# 3. For each column in matrix B, calculate the average.
# Using np.mean() with axis=0 calculates the mean for each column.
column_averages_B = np.mean(B, axis=0)
print("3. Average of each column in Matrix B:\n", column_averages_B)

# Identify which column has the lowest mean value.
lowest_mean_column_index = np.argmin(column_averages_B)
# Add 1 to the index to make it 1-based for user readability.
print(f"   Column with the lowest mean value: Column {lowest_mean_column_index + 1}")
print("\n" + "="*30 + "\n")

# 4. Number of elements of B greater than 5.
# Create a boolean array where elements greater than 5 are True, others are False.
# Then sum the boolean array (True counts as 1, False as 0) to get the count.
elements_greater_than_5_B = np.sum(B > 5)
print("4. Number of elements in Matrix B greater than 5:\n", elements_greater_than_5_B)
print("\n" + "="*30 + "\n")

# 5. Compute A * B (matrix multiplication).
# For matrix multiplication A*B, the number of columns in A must equal the number of rows in B.
# A has shape (3,) and B has shape (3, 5).
# np.dot handles 1D arrays by treating the first array as a row vector and the second as a column vector
# or by performing a dot product if both are 1D.
# In this case, A (1x3) will be multiplied by B (3x5) resulting in a (1x5) matrix.
# To make it explicit for matrix multiplication, A can be reshaped to (1, 3).
# However, np.dot(A, B) correctly performs the operation as (1x3) @ (3x5) -> (1x5).
# Let's verify dimensions before multiplication.
# A_reshaped = A.reshape(1, 3) # This would make it explicitly 2D
# result_A_times_B = np.dot(A_reshaped, B)

# Using np.dot directly with 1D array A and 2D array B:
# A is (3,), B is (3,5). The dot product will treat A as a row vector (1,3).
# The result will be a (1,5) array.
result_A_times_B = np.dot(A, B)
print("5. Result of A * B (matrix multiplication):\n", result_A_times_B)
print("\n" + "="*30 + "\n")

# 6. Compute C + 2C.
# This is equivalent to 3C.
result_C_plus_2C = C + 2 * C
print("6. Result of C + 2C:\n", result_C_plus_2C)
print("\n" + "="*30 + "\n")

--- Initial Matrices ---
Matrix A:
 [2 4 6]
Matrix B:
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]
Matrix C:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Matrix D:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


1. Result of 5A + 2:
 [12 22 32]


2. Sum of each row in Matrix B:
 [20 45 70]


3. Average of each column in Matrix B:
 [ 7.  8.  9. 10. 11.]
   Column with the lowest mean value: Column 1


4. Number of elements in Matrix B greater than 5:
 11


5. Result of A * B (matrix multiplication):
 [104 116 128 140 152]


6. Result of C + 2C:
 [[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


